// Add user-provided websites to each category's sites array.
export const categories = [
  {
    id: 'personal',
    title: '自己的网站',
    illustration: '/illustrations/personal.webp',
    sites: [
      { id: 'ai-coding', name: '安静 AI-Coding', domain: 'ai-coding.anjing.cc' },
      { id: 'aigc', name: '安静 AIGC', domain: 'aigc.anjing.cc' },
      { id: 'company', name: '公司信息看板', domain: 'company.anjing.cc' },
      { id: 'context', name: '项目上下文工程', domain: 'context.anjing.cc' },
      { id: 'feedme', name: 'FeedMe 像素订单', domain: 'feedme.anjing.cc' },
      { id: 'github-journey', name: 'GitHub 之旅', domain: 'github-journey.anjing.cc' },
      { id: 'happy-finance', name: '金融之旅', domain: 'happy-finance.anjing.cc' },
      { id: 'happy-github', name: 'GitHub 之旅', domain: 'happy-github.anjing.cc' },
      { id: 'happy-journey', name: '人生记录', domain: 'happy-journey.anjing.cc' },
      { id: 'happy-llm', name: '大模型之旅', domain: 'happy-llm.anjing.cc' },
      { id: 'hub', name: '提示词 Hub', domain: 'hub.anjing.cc' },
      { id: 'music', name: '安静音乐', domain: 'music.anjing.cc' },
      { id: 'nav', name: '安静导航', domain: 'nav.anjing.cc' },
      { id: 'resume', name: '个人简历', domain: 'resume.anjing.cc' },
      { id: 'richfree', name: 'Richfree 财富自由', domain: 'richfree.anjing.cc' },
      { id: 'ruankao', name: '软考笔记', domain: 'ruankao.anjing.cc' },
      { id: 'site', name: '安静的微缩世界', domain: 'site.anjing.cc' },
    ],
  },
  {
    id: 'tools',
    title: '工具网站',
    illustration: '/illustrations/tools.webp',
    sites: [],
  },
  {
    id: 'work',
    title: '公司网站',
    illustration: '/illustrations/work.webp',
    sites: [],
  },
  {
    id: 'wander',
    title: '乱七八糟看的网站',
    illustration: '/illustrations/wander.webp',
    sites: [],
  },
]
