// Add user-provided websites to each category's sites array.
export const categories = [
  {
    id: 'personal',
    title: '自己的网站',
    illustration: '/illustrations/personal.webp',
    sites: [
      { id: 'ai-coding', name: 'ai-coding', domain: 'ai-coding.anjing.cc' },
      { id: 'aigc', name: 'aigc', domain: 'aigc.anjing.cc' },
      { id: 'company', name: 'company', domain: 'company.anjing.cc' },
      { id: 'context', name: 'context', domain: 'context.anjing.cc' },
      { id: 'feedme', name: 'feedme', domain: 'feedme.anjing.cc' },
      { id: 'github-journey', name: 'github-journey', domain: 'github-journey.anjing.cc' },
      { id: 'happy-finance', name: 'happy-finance', domain: 'happy-finance.anjing.cc' },
      { id: 'happy-github', name: 'happy-github', domain: 'happy-github.anjing.cc' },
      { id: 'happy-journey', name: 'happy-journey', domain: 'happy-journey.anjing.cc' },
      { id: 'happy-llm', name: 'happy-llm', domain: 'happy-llm.anjing.cc' },
      { id: 'hub', name: 'hub', domain: 'hub.anjing.cc' },
      { id: 'music', name: 'music', domain: 'music.anjing.cc' },
      { id: 'nav', name: 'nav', domain: 'nav.anjing.cc' },
      { id: 'resume', name: 'resume', domain: 'resume.anjing.cc' },
      { id: 'richfree', name: 'richfree', domain: 'richfree.anjing.cc' },
      { id: 'ruankao', name: 'ruankao', domain: 'ruankao.anjing.cc' },
      { id: 'site', name: 'site', domain: 'site.anjing.cc' },
    ],
  },
  {
    id: 'tools',
    title: '工具网站',
    illustration: '/illustrations/tools.webp',
    sites: [],
  },
  {
    id: 'work',
    title: '公司网站',
    illustration: '/illustrations/work.webp',
    sites: [],
  },
  {
    id: 'wander',
    title: '乱七八糟看的网站',
    illustration: '/illustrations/wander.webp',
    sites: [],
  },
]
